# File: config/common-service.yml in Git repo
postgres-username: ${postgres-username}
postgres-password: ${postgres-password}
mongodb-username: ${mongodb-username}
mongodb-password: ${mongodb-password}
kafka-saslUser: ${kafka-saslUser}
kafka-saslPassword: ${kafka-saslPassword}

spring:
  datasource:
    url: jdbc:postgresql://aurumstreet-pg.ch2ewgs0kpm0.ap-south-1.rds.amazonaws.com:5432/aurumdb
    username: ${postgres-username}
    password: ${postgres-password}
  data:
    mongodb:
      uri: mongodb+srv://${mongodb-username}:${mongodb-password}@aurumstreet.7abmeup.mongodb.net/aurum_db
